<?php
require_once __DIR__ . '/includes/session.php';
require_once __DIR__ . '/includes/db.php';
$projects = $gallery = $testimonials = [];
try {
    $projects = db()->query("SELECT * FROM projects ORDER BY created_at DESC")->fetchAll();
    $gallery = db()->query("SELECT g.*, p.project_name FROM gallery g LEFT JOIN projects p ON p.id=g.project_id ORDER BY g.uploaded_at DESC LIMIT 12")->fetchAll();
    $testimonials = db()->query("SELECT * FROM testimonials WHERE approved=1 ORDER BY created_at DESC LIMIT 3")->fetchAll();
} catch (Throwable $e) { /* Site remains viewable before the SQL import. */ }
$project = $projects[0] ?? ['project_name'=>"Papu's Residency",'location'=>'Davangere, Karnataka','description'=>'A thoughtfully designed residential project offering spacious homes, modern architecture, superior construction quality and premium amenities.','status'=>'Ongoing','thumbnail'=>'assets/projects/papus-residency-1.jpg'];
if (!$gallery) foreach (glob(__DIR__ . '/assets/gallery/*.{jpg,jpeg,png,webp}', GLOB_BRACE) ?: [] as $image) $gallery[] = ['image'=>'assets/gallery/' . basename($image)];
if (!$testimonials) $testimonials = [['customer_name'=>'Ramesh Kumar','review'=>'Excellent construction quality and professional service throughout the project. Highly recommended.','rating'=>5],['customer_name'=>'Priya S.','review'=>'Transparent documentation and timely updates. We are extremely satisfied with our investment.','rating'=>5],['customer_name'=>'Naveen H.','review'=>'The team was supportive from booking until possession. Quality exceeded expectations.','rating'=>5]];
$pageTitle = 'Yashaswi Groups of Construction'; require __DIR__ . '/includes/header.php';
?>
<div class="loader"><img src="<?= url('assets/logo/yashaswi-logo.png') ?>" alt="Yashaswi Logo"><h2>Loading...</h2></div>
<section id="home" class="hero"><div class="hero-overlay"></div><div class="hero-content"><span class="hero-tag">PREMIUM CONSTRUCTION COMPANY</span><h1>Building Dreams Into Reality</h1><h2>Yashaswi Groups of Construction</h2><p>Delivering premium residential apartments, luxury duplex homes, commercial buildings, and modern architectural excellence in Davangere.</p><div class="hero-buttons"><a href="<?= url('projects.php') ?>" class="btn btn-primary">Explore Projects</a><a href="#contact" class="btn btn-outline">Book Site Visit</a></div></div><div class="scroll-indicator"><i class="fa-solid fa-angles-down"></i></div></section>
<section id="about" class="about"><div class="container about-container"><div class="about-image"><img src="<?= url('assets/about/about.jpg') ?>" alt="About Yashaswi Groups"></div><div class="about-content"><span class="section-tag">ABOUT US</span><h2>Creating Homes That Inspire Generations</h2><p>Yashaswi Groups of Construction is committed to delivering premium residential and commercial developments with exceptional engineering, modern architecture and uncompromising construction quality.</p><p>Our vision is to provide every customer with a home that combines comfort, safety, elegance and long-term value.</p></div></div></section>
<section id="projects" class="projects"><div class="container"><div class="section-heading"><span>OUR PROJECTS</span><h2><?= e($project['project_name']) ?></h2><p>Premium spaces designed for comfort, luxury and long-term value.</p></div><div class="project-wrapper"><div class="project-image"><img src="<?= url($project['thumbnail']) ?>" alt="<?= e($project['project_name']) ?>"></div><div class="project-content"><h3><?= e($project['status']) ?> Project</h3><p><?= e($project['description']) ?></p><div class="project-details"><div class="detail-card"><i class="fa-solid fa-location-dot"></i><div><h4>Project Location</h4><p><?= e($project['location']) ?></p></div></div><div class="detail-card"><i class="fa-solid fa-building"></i><div><h4>Property Type</h4><p>Premium Construction</p></div></div></div><a href="#contact" class="btn btn-primary">Schedule Site Visit</a></div></div></div></section>
<section id="gallery" class="gallery"><div class="container"><div class="section-heading"><span>PROJECT GALLERY</span><h2>Explore Our Work</h2><p>A glimpse of our premium residential projects.</p></div><div class="gallery-grid"><?php foreach ($gallery as $item): ?><img src="<?= url($item['image']) ?>" alt="Construction gallery image"><?php endforeach; ?></div><p style="text-align:center;margin-top:28px"><a class="btn btn-primary" href="<?= url('gallery.php') ?>">View Gallery</a></p></div></section>
<section id="amenities" class="amenities"><div class="container"><div class="section-heading"><span>LUXURY AMENITIES</span><h2>Experience Modern Living</h2></div><div class="amenities-grid"><?php foreach (['Covered Parking'=>'car','24×7 Security'=>'shield-halved','CCTV Monitoring'=>'video','High Speed Lift'=>'elevator','Kids Play Area'=>'child-reaching','Landscape Garden'=>'tree','Power Backup'=>'bolt','24 Hour Water'=>'droplet'] as $name=>$icon): ?><div class="amenity-card"><i class="fa-solid fa-<?= $icon ?>"></i><h3><?= $name ?></h3><p>Designed for your comfort, convenience and safety.</p></div><?php endforeach; ?></div></div></section>
<section class="testimonials"><div class="container"><div class="section-heading"><span>TESTIMONIALS</span><h2>What Our Customers Say</h2></div><div class="testimonial-grid"><?php foreach ($testimonials as $item): ?><div class="testimonial-card"><div class="stars"><?= str_repeat('★', max(1, min(5, (int)$item['rating']))) ?></div><p>“<?= e($item['review']) ?>”</p><h4><?= e($item['customer_name']) ?></h4><span>Customer</span></div><?php endforeach; ?></div></div></section>
<section id="contact" class="contact"><div class="container contact-container"><div class="contact-info"><span>CONTACT US</span><h2>Let's Build Your Dream Home</h2><p>Visit our office or contact us today to schedule your site visit.</p><div class="contact-item"><i class="fa-solid fa-location-dot"></i><div><h4>Office Address</h4><p>Building #80, 2nd Cross, 1st Main, S.O.G Colony, Davangere</p></div></div><div class="contact-item"><i class="fa-solid fa-phone"></i><div><h4>Call Us</h4><p>+91 8095406405</p></div></div><div class="contact-item"><i class="fa-solid fa-envelope"></i><div><h4>Email</h4><p>Raghavendrams809@gmail.com</p></div></div></div><div class="contact-form"><?php if ($message = flash('enquiry')): ?><p class="form-message success"><?= e($message) ?></p><?php endif; ?><form action="<?= url('api/enquiry.php') ?>" method="post"><input type="hidden" name="csrf" value="<?= csrf_token() ?>"><input type="text" name="name" placeholder="Your Name" maxlength="100" required><input type="email" name="email" placeholder="Email Address" maxlength="150" required><input type="tel" name="phone" placeholder="Phone Number" maxlength="25" required><textarea name="message" rows="6" placeholder="Write Your Message" maxlength="2000"></textarea><button type="submit" class="btn btn-primary">Submit Enquiry</button></form></div></div></section>
<section class="map"><iframe src="https://maps.google.com/maps?q=14.422519,75.941456&z=16&output=embed" loading="lazy" allowfullscreen title="Yashaswi Groups location"></iframe></section>
<?php require __DIR__ . '/includes/footer.php'; ?>
